export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_IP_ADDRESS = 'SET_IP_ADDRESS';
export const RESET_AUTH = 'RESET_AUTH';
export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';
export const SET_REFRESH_TOKE = 'SET_REFRESH_TOKE';
export const SET_SEARCH_LOCATION = 'SET_SEARCH_LOCATION'
export const SET_PROFILE = 'SET_PROFILE'

export const SET_ACC_DETAILS = 'SET_ACC_DETAILS';
export const DEFAULT_ACC_INDEX = 'DEFAULT_ACC_INDEX';
export const HAS_DEBIT_CARD = 'HAS_DEBIT_CARD';

export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER'

export const SET_META_DATA = 'SET_META_DATA'
export const SET_MPIN_DATA = 'SET_MPIN_DATA'

export const SET_USER_DETAILS = 'SET_USER_DETAILS'

export const SET_BIOMETRIC_ENABLED = 'SET_BIOMETRIC_ENABLED'

export const SET_SELECTED_AVATAR = 'SET_SELECTED_AVATAR'

export const SET_SELECTED_RANDOM_KEY = 'SET_SELECTED_RANDOM_KEY'

export const SET_USER_LOGIN_FIRST = 'SET_USER_LOGIN_FIRST'
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE'

export const SET_ACC_REFRESH= 'SET_ACC_REFRESH'